type = "webpack"
name = "flareact"
account_id = "691a3156e374317f2c626559557a6f12"
workers_dev = true
zone_id = "cd7d068de3012345da9420df9514dad0"
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
