type = "webpack"
name = "flareact"
account_id = "d9c4a171c4a0d0a8e6f8204ae9ba0638"
workers_dev = true
zone_id = "cd7d068de3012345da9420df9514dad0"
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
