type = "webpack"
name = "flareact"
account_id = "9326ea8155c740226674552c41ac809c"
workers_dev = true
zone_id = "cd7d068de3012345da9420df9514dad0"
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
